### ISSUE TITLE
Travis CI ShellCommandUnresponsiveException

### ISSUE THREAD

**Issue by luisramalho** [paulirotta/cascade#3]
There seems to be a problem with gradle commands and API 23 / ARM (armeabi-v7a)

https://code.google.com/p/android/issues/detail?id=190200

**Comment by paulirotta** [comment]
Yeah, we use API23 to compile, but only 19 emulator. Even that is marginal- Travis is just too slow and perhaps we should drop back to 15 for better reliability. I think there is something else also going on, will try to look at it once other smoke clears
(from .travis.yml)
..
- EMULATOR=android-19
